language: python
python:
    - 3.6

services:
  - postgresql


before_script:
  - psql -c 'CREATE DATABASE travisdb' -U postgres

#set environment variables
env:
    - APP_SETTINGS=development
    - DATABASE_URL=postgresql://postgres:@localhost:5432/travisdb

# command to run tests
script:
    - python manage.py test
#    - python manage.py test --exe --with-coverage --cover-package=test_webapp
#    - coveralls
#after_success: "coveralls"