language: python
python:
    - 3.6

# command to run tests
script:
    - python manage.py test
#    - python manage.py test --exe --with-coverage --cover-package=test_webapp
#    - coveralls
#after_success: "coveralls"