language: python
python:
    - 3.6

services:
  - postgresql

#set environment variables
env:
    - APP_SETTINGS=development

before_script:
  - cp config/database.yml.travis config/database.yml

# command to run tests
script:
    - python manage.py test
#    - python manage.py test --exe --with-coverage --cover-package=test_webapp
#    - coveralls
#after_success: "coveralls"