"""empty message

Revision ID: 84af270a82e1
Revises: 75115b32e621
Create Date: 2017-11-20 11:24:29.307183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84af270a82e1'
down_revision = '75115b32e621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'filename')
    # ### end Alembic commands ###
