"""empty message

Revision ID: c38b0aaf4bd4
Revises: cafbf0c616fe
Create Date: 2018-02-01 15:46:19.140770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38b0aaf4bd4'
down_revision = 'cafbf0c616fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_category_uc', 'categories', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_category_uc', 'categories', type_='unique')
    # ### end Alembic commands ###
