"""empty message

Revision ID: cafbf0c616fe
Revises: 99b88ad13273
Create Date: 2018-02-01 12:22:15.150297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafbf0c616fe'
down_revision = '99b88ad13273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_category_title_uc', 'recipes', ['category_id', 'title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_category_title_uc', 'recipes', type_='unique')
    # ### end Alembic commands ###
